- name: Preconfigure jackd
  ansible.builtin.debconf:
    name: jackd2
    question: jackd/tweak_rt_limits
    value: 'true'
    vtype: select
  become: true

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - jackd2
    state: present
    update_cache: true
  become: true

- name: Create streaming user
  ansible.builtin.user:
    name: streaming
    state: present
    shell: /usr/sbin/nologin
    system: true
    groups:
      - audio
    comment: Streaming services user
  become: true

- name: Create systemd service
  ansible.builtin.template:
    src: templates/jackd.service.j2
    dest: /etc/systemd/system/jackd.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Enable and start systemd service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: jackd.service
    daemon_reload: true
  become: true
